"""
report_generator.py
---------------------
Builds a clean PDF report for one session: attendance, phone-use alerts,
drowsiness alerts, and an engagement summary. Pulls from the same
database the dashboard reads from, so the PDF and the live dashboard can
never show different numbers.

Used by backend/app.py's /api/report/<session_id>/pdf endpoint.
"""

from fpdf import FPDF
from datetime import datetime
import database as db

TEAL  = (79, 209, 197)
DARK  = (30, 38, 48)
GREY  = (110, 120, 135)
LIGHT = (240, 242, 246)
RED   = (230, 60, 70)
AMBER = (230, 150, 30)


class ReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(*DARK)
        self.cell(0, 10, "ClassSentinel - Session Report", ln=True)
        self.set_draw_color(*TEAL)
        self.set_line_width(0.8)
        self.line(10, 20, 200, 20)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*GREY)
        self.cell(0, 10, f"Generated by ClassSentinel  |  Page {self.page_no()}", align="C")

    def section_title(self, text):
        self.ln(4)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*DARK)
        self.cell(0, 8, text, ln=True)
        self.set_draw_color(*LIGHT)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def table_header(self, widths, labels):
        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(*DARK)
        self.set_text_color(255, 255, 255)
        for w, label in zip(widths, labels):
            self.cell(w, 8, label, border=0, fill=True, align="L")
        self.ln()

    def table_row(self, widths, values, fill):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*DARK)
        self.set_fill_color(*LIGHT) if fill else self.set_fill_color(255, 255, 255)
        for w, val in zip(widths, values):
            self.cell(w, 7, str(val), border=0, fill=True, align="L")
        self.ln()


def generate_report_pdf(session_id, output_path):
    session  = db.get_session(session_id)
    students = db.get_student_summary(session_id)
    phone    = db.get_phone_alerts(session_id, limit=100000)
    drowsy   = db.get_drowsy_alerts(session_id, limit=100000)
    summary  = db.get_summary(session_id)

    pdf = ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Session info ──────────────────────────────────────────
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*GREY)
    start = session["start_time"] if session else "-"
    end   = session["end_time"] if session and session["end_time"] else "In progress"
    pdf.cell(0, 6, f"Session #{session_id}   |   Start: {start}   |   End: {end}", ln=True)
    pdf.ln(2)

    # ── Summary cards (as a compact row) ────────────────────────
    pdf.section_title("Summary")
    widths = [47, 47, 47, 47]
    labels = ["Students Present", "Phone Alerts", "Drowsy Alerts", "Avg Engagement"]
    values = [summary["total_marked"], summary["phone_alerts"], summary["drowsy_alerts"], f"{summary['avg_engagement']}%"]
    pdf.table_header(widths, labels)
    pdf.table_row(widths, values, fill=True)
    pdf.ln(4)

    # ── Unified per-student summary — the main table ────────────
    pdf.section_title(f"Student Summary ({len(students)} present)")
    if students:
        widths = [28, 40, 22, 22, 22, 22, 24]
        pdf.table_header(widths, ["ID", "Name", "Attend.", "First Seen", "Phone", "Drowsy", "Engage."])
        for i, s in enumerate(students):
            pdf.table_row(widths, [
                s["student_id"], s["student_name"], s["attendance"],
                s["first_seen"], s["phone_alerts"], s["drowsy_alerts"], f"{s['engagement']}%"
            ], fill=(i % 2 == 0))
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*GREY)
        pdf.cell(0, 6, "No students detected in this session.", ln=True)

    # ── Detailed logs (appendix) ─────────────────────────────────
    pdf.ln(4)
    pdf.section_title(f"Detailed Phone Alert Log ({len(phone)})")
    if phone:
        widths = [40, 70]
        pdf.table_header(widths, ["Time", "Student"])
        for i, row in enumerate(phone):
            student = row["student_name"] if row["student_name"] else "Unidentified"
            pdf.table_row(widths, [row["time"], student], fill=(i % 2 == 0))
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*GREY)
        pdf.cell(0, 6, "No phone usage detected.", ln=True)

    pdf.section_title(f"Detailed Drowsiness Log ({len(drowsy)})")
    if drowsy:
        widths = [40, 70]
        pdf.table_header(widths, ["Time", "Student"])
        for i, row in enumerate(drowsy):
            student = row["student_name"] if row["student_name"] else "Unidentified"
            pdf.table_row(widths, [row["time"], student], fill=(i % 2 == 0))
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*GREY)
        pdf.cell(0, 6, "No drowsiness detected.", ln=True)

    pdf.output(output_path)
    return output_path